version: '3.8'

services:
  kds:
    image: kds_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=OrderManagementDb;User=sa;Password=Str0ngP@ssw0rd!;TrustServerCertificate=True;
      - DOTNET_RUNNING_IN_CONTAINER=true

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Str0ngP@ssw0rd!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
